### ISSUE TITLE
Menjelaskan Mata Kuliah dan Prasyarat

### ISSUE THREAD

**Issue by pascalalfadian** [pascalalfadian/eJuklak#2]
Di subbab 2.5.4, 2.5.3, dll: Cara menjelaskan MK dan prasyaratnya bisa diperbagus lagi (sekarang: 1 baris untuk kode & nama, 1 baris untuk prasyarat & penjelasan.

**Comment by pascalalfadian** [comment]
Untuk poin 1, bisa di restruktur menjadi seperti ini:

```markdown
| Kode MK | Prasyarat | Nama dan Deskripsi Mata Kuliah |
| ------- | --------- | ------------------------------ |
| AMS121  | -         | **KALKULUS 1 _(CALCULUS 1)_**  Fungsi, limit dan kekontinuan fungsi, turunan dan penggunaannya, dan konsep dasar dari integral. |
| AMS124  | AMS123    | **MATEMATIKA DISKRET _(DISCRETE MATHEMATICS)_**  Logika dan bukti, himpunan dan fungsi, induksi dan rekursi, masalah pencacahan (counting), dan teori graf. |
| ...     | ...       | ...                            |
```

**Comment by vaniachoi** [comment]
ah jadi 3 kolom ya pak? sip sip pak. ini diperbaiki nya untuk presentasi besok atau untuk versi selanjutnya ya sebaiknya?

**Comment by pascalalfadian** [comment]
Wah, semua fork dapat notifnya ya? Ya. Untuk ini sih opsional, dan khusus yang menggunakan tabel saja. Kalau mau diikuti / tidak diikuti tidak apa2. Sekalian saya update contoh di atas ya, Trims.

**Comment by pascalalfadian** [comment]
@vaniachoi dan tidak untuk presentasi besok, karena seharusnya tim kalian kan sudah rilis sebelum issue ini keluar.

**Comment by vaniachoi** [comment]
oke pak terima kasih :+1:
